"""autogenerated by genpy from movetest/Coordinate.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Coordinate(genpy.Message):
  _md5sum = "ad3abf38e683f2615b659787ef3c61f5"
  _type = "movetest/Coordinate"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint64 xcoordinate
uint64 ycoordinate
uint64 zcoordinate

uint64 roll
uint64 pitch
uint64 yaw

"""
  __slots__ = ['xcoordinate','ycoordinate','zcoordinate','roll','pitch','yaw']
  _slot_types = ['uint64','uint64','uint64','uint64','uint64','uint64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       xcoordinate,ycoordinate,zcoordinate,roll,pitch,yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Coordinate, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.xcoordinate is None:
        self.xcoordinate = 0
      if self.ycoordinate is None:
        self.ycoordinate = 0
      if self.zcoordinate is None:
        self.zcoordinate = 0
      if self.roll is None:
        self.roll = 0
      if self.pitch is None:
        self.pitch = 0
      if self.yaw is None:
        self.yaw = 0
    else:
      self.xcoordinate = 0
      self.ycoordinate = 0
      self.zcoordinate = 0
      self.roll = 0
      self.pitch = 0
      self.yaw = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6Q.pack(_x.xcoordinate, _x.ycoordinate, _x.zcoordinate, _x.roll, _x.pitch, _x.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.xcoordinate, _x.ycoordinate, _x.zcoordinate, _x.roll, _x.pitch, _x.yaw,) = _struct_6Q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6Q.pack(_x.xcoordinate, _x.ycoordinate, _x.zcoordinate, _x.roll, _x.pitch, _x.yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.xcoordinate, _x.ycoordinate, _x.zcoordinate, _x.roll, _x.pitch, _x.yaw,) = _struct_6Q.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6Q = struct.Struct("<6Q")
